CREATE TABLE TAKEOUTENTITY (ID BIGINT NOT NULL, STARTDATE DATE, TOTALQUERIES INTEGER, TOTALSBYDATE JSON, PRIMARY KEY (ID))
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(38), PRIMARY KEY (SEQ_NAME))
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0)
